### ISSUE TITLE
WMM2015  Magnetic Model needs adding

### ISSUE THREAD

**Issue by muzbox** [sibartlett/Geo#21]
The 2015 magnetic model has been released.

http://www.ngdc.noaa.gov/geomag/WMM/

Is it possible to get this translated into a model file in the library?

Is it only the creation of a Wmm2015.cs that is needed? I am not sure how to translate the released information into this file

thanks

**Comment by sibartlett** [comment]
I have released a new version of Geo with the 2015 magnetic model.

**Comment by muzbox** [comment]
Thanks for the quick update!!

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Mon, Dec 28, 2015 at 10:44 PM -0800, "Simon Bartlett" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have released a new version of Geo with the 2015 magnetic model.

-

**Comment by sibartlett** [comment]
I noticed that Geo has been missing this model for a year... you must be the only person using this feature! lol :smile:
