### ISSUE TITLE
TrkSeg can be empty on GPX 1.1

### ISSUE THREAD

**Issue by alex75ita** [sibartlett/Geo#23]
With a GPX 1.1 you have this error parsing a GPX file:
**NullReferenceException**
if the file contains an empty **trkseg** element (\<trkseg/\>)

**trkseg** can be an empty element: http://www.topografix.com/GPX/1/1/#type_trksegType
(it is a complex element and contains a sequence of [0..\*] **trkpt** elements)

The problem is in **Gps\Serialization\Gpx11Serializer.cs**
```
private static void ParseTracks(GpxFile xml, GpsData data)
[...]
foreach (var wptType in trksegType.trkpt)
```
_trksegType.trkpt_ is null if _trkseg_ element doesn't contain any point.

(problem exists in version 0.13 and 0.14)

Alessandro

**Comment by alex75ita** [comment]
A segment is added in track only for adding points, so it can be ignored if it hasn't points.
Proposed solution.
from: 
`foreach (var trksegType in trkType.trkseg)`
to:
`foreach (var trksegType in trkType.trkseg.Where(seg => seg.trkpt != null))`

**Comment by sibartlett** [comment]
0.14.1 pushed to NuGet.
