### ISSUE TITLE
Want extensions of Gpx11.GpxWaypoint

### ISSUE THREAD

**Issue by abnaki** [sibartlett/Geo#25]
I am very interested in a practical application of the _extensions_ property of 
Geo.Gps.Serialization.Xml.Gpx.Gpx11.GpxWaypoint.   [It's documented here.](http://www.topografix.com/GPX/1/1/#type_extensionsType)
In your file, it is commented out.  It has been 4 years.   Do you suggest I work on a branch here or should I fork?  Thanks.

**Comment by sibartlett** [comment]
I'm certainly open to a pull request; support for GPX extensions would be nice.

You can fork the repository, and open a pull request when you're ready or require feedback.
