### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by mfeingol** [sibartlett/Geo#33]
I tried compiling the GEO library for a .NET Standard 1.4 library, and it just had a few small issues with some reflection code. Should be pretty straightforward to ship a nuget package supporting .NET Standard.

Thanks!

**Comment by mfeingol** [comment]
Addressed in https://github.com/sibartlett/Geo/pull/37

**Comment by sibartlett** [comment]
Merged in: 058e413574ffe8f4c958536783a4ab81283b7c70
