### ISSUE TITLE
.net core support (or net standard)

### ISSUE THREAD

**Issue by aluevano** [sibartlett/Geo#53]
Does this library support .net core or .net standard?
Considering this library for an open source project but docs do not reflect one way or the other the support for core / standard.

thanks.

**Comment by sibartlett** [comment]
Yes, it supports both core and standards

**Comment by wegylexy** [comment]
https://github.com/sibartlett/Geo/blob/b66184d0663bba441be33c876c382263284d468d/Geo/Geo.csproj#L15
